"""
export_utils.py
Converts a markdown report string to PDF and DOCX bytes (in-memory).
"""
import io
import re
from datetime import datetime


def _parse_markdown(text: str):
    """
    Returns a list of (type, content) tuples:
      ('h1', str), ('h2', str), ('bullet', str), ('text', str), ('blank',)
    """
    lines = []
    for raw in text.split("\n"):
        line = raw.rstrip()
        if line.startswith("## "):
            lines.append(("h2", line[3:].strip()))
        elif line.startswith("# "):
            lines.append(("h1", line[2:].strip()))
        elif line.startswith("### "):
            lines.append(("h2", line[4:].strip()))
        elif re.match(r"^[\*\-\•]\s+", line):
            lines.append(("bullet", re.sub(r"^[\*\-\•]\s+", "", line).strip()))
        elif re.match(r"^\s{2,}[o\-]\s+", line):
            lines.append(("subbullet", re.sub(r"^\s+[o\-]\s+", "", line).strip()))
        elif line == "":
            lines.append(("blank",))
        else:
            lines.append(("text", line))
    return lines


def _strip_bold(text: str) -> str:
    """Remove **bold** markers for plain-text contexts."""
    return re.sub(r"\*\*(.*?)\*\*", r"\1", text)


# ── PDF ──────────────────────────────────────────────────────────────────────

def report_to_pdf(report_text: str, sprint_name: str = "Sprint Report") -> bytes:
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.lib import colors
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, HRFlowable
    )

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=letter,
        leftMargin=inch, rightMargin=inch,
        topMargin=inch, bottomMargin=inch
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "ReportTitle", parent=styles["Normal"],
        fontSize=20, fontName="Helvetica-Bold",
        textColor=colors.HexColor("#1a1a2e"),
        spaceAfter=4
    )
    meta_style = ParagraphStyle(
        "Meta", parent=styles["Normal"],
        fontSize=9, fontName="Helvetica",
        textColor=colors.HexColor("#888888"),
        spaceAfter=12
    )
    h1_style = ParagraphStyle(
        "H1", parent=styles["Normal"],
        fontSize=14, fontName="Helvetica-Bold",
        textColor=colors.HexColor("#1a1a2e"),
        spaceBefore=16, spaceAfter=4
    )
    h2_style = ParagraphStyle(
        "H2", parent=styles["Normal"],
        fontSize=12, fontName="Helvetica-Bold",
        textColor=colors.HexColor("#2c3e50"),
        spaceBefore=10, spaceAfter=2
    )
    body_style = ParagraphStyle(
        "Body", parent=styles["Normal"],
        fontSize=10, fontName="Helvetica",
        textColor=colors.HexColor("#333333"),
        spaceAfter=4, leading=14
    )
    bullet_style = ParagraphStyle(
        "Bullet", parent=styles["Normal"],
        fontSize=10, fontName="Helvetica",
        textColor=colors.HexColor("#333333"),
        leftIndent=16, spaceAfter=3,
        leading=14, bulletIndent=4
    )
    sub_style = ParagraphStyle(
        "SubBullet", parent=styles["Normal"],
        fontSize=9, fontName="Helvetica",
        textColor=colors.HexColor("#555555"),
        leftIndent=32, spaceAfter=2,
        leading=13, bulletIndent=20
    )

    story = []

    # Header
    story.append(Paragraph("📋 AI Product Brief", title_style))
    story.append(Paragraph(
        f"Generated on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
        meta_style
    ))
    story.append(HRFlowable(width="100%", thickness=1.5,
                             color=colors.HexColor("#3b82f6"), spaceAfter=12))

    # Content
    for item in _parse_markdown(report_text):
        kind = item[0]
        text = _strip_bold(item[1]) if len(item) > 1 else ""
        text = text.replace("**", "")

        if kind == "h1":
            story.append(Paragraph(text, h1_style))
        elif kind == "h2":
            story.append(Paragraph(text, h2_style))
        elif kind == "bullet":
            story.append(Paragraph(f"• {text}", bullet_style))
        elif kind == "subbullet":
            story.append(Paragraph(f"◦ {text}", sub_style))
        elif kind == "text" and text:
            story.append(Paragraph(text, body_style))
        elif kind == "blank":
            story.append(Spacer(1, 4))

    # Footer
    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=0.5,
                             color=colors.HexColor("#cccccc"), spaceAfter=6))
    story.append(Paragraph(
        "Generated by StandupAI",
        meta_style
    ))

    doc.build(story)
    return buf.getvalue()


# ── DOCX ─────────────────────────────────────────────────────────────────────

def report_to_docx(report_text: str, sprint_name: str = "Sprint Report") -> bytes:
    from docx import Document
    from docx.shared import Pt, RGBColor, Inches
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement

    doc = Document()

    # Page margins
    for section in doc.sections:
        section.top_margin    = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin   = Inches(1)
        section.right_margin  = Inches(1)

    def set_run_color(run, hex_color):
        r, g, b = int(hex_color[0:2],16), int(hex_color[2:4],16), int(hex_color[4:6],16)
        run.font.color.rgb = RGBColor(r, g, b)

    def add_hr(doc):
        p = doc.add_paragraph()
        p.paragraph_format.space_before = Pt(2)
        p.paragraph_format.space_after  = Pt(2)
        pPr = p._p.get_or_add_pPr()
        pBdr = OxmlElement('w:pBdr')
        bottom = OxmlElement('w:bottom')
        bottom.set(qn('w:val'),   'single')
        bottom.set(qn('w:sz'),    '6')
        bottom.set(qn('w:space'), '1')
        bottom.set(qn('w:color'), '3b82f6')
        pBdr.append(bottom)
        pPr.append(pBdr)

    # Title
    title_p = doc.add_paragraph()
    title_r = title_p.add_run("📋 AI Product Brief")
    title_r.font.size = Pt(20)
    title_r.bold = True
    set_run_color(title_r, "1a1a2e")

    meta_p = doc.add_paragraph()
    meta_r = meta_p.add_run(
        f"Generated on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}"
    )
    meta_r.font.size = Pt(9)
    set_run_color(meta_r, "888888")

    add_hr(doc)

    # Body
    for item in _parse_markdown(report_text):
        kind = item[0]
        raw  = item[1] if len(item) > 1 else ""

        if kind == "h1":
            h = doc.add_heading(level=1)
            h.clear()
            run = h.add_run(_strip_bold(raw))
            run.font.size = Pt(14)
            run.bold = True
            set_run_color(run, "1a1a2e")

        elif kind == "h2":
            h = doc.add_heading(level=2)
            h.clear()
            run = h.add_run(_strip_bold(raw))
            run.font.size = Pt(12)
            run.bold = True
            set_run_color(run, "2c3e50")

        elif kind == "bullet":
            p = doc.add_paragraph(style="List Bullet")
            _add_mixed_runs(p, raw)
            p.paragraph_format.left_indent = Inches(0.25)

        elif kind == "subbullet":
            p = doc.add_paragraph(style="List Bullet 2")
            _add_mixed_runs(p, raw)
            p.paragraph_format.left_indent = Inches(0.5)

        elif kind == "text" and raw:
            p = doc.add_paragraph()
            _add_mixed_runs(p, raw)
            p.paragraph_format.space_after = Pt(4)

        elif kind == "blank":
            doc.add_paragraph().paragraph_format.space_after = Pt(2)

    # Footer line
    add_hr(doc)
    footer_p = doc.add_paragraph()
    footer_r = footer_p.add_run("Generated by StandupAI")
    footer_r.font.size = Pt(9)
    set_run_color(footer_r, "888888")

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()


def _add_mixed_runs(paragraph, text: str):
    """Parse **bold** segments and add as separate runs."""
    from docx.shared import Pt
    parts = re.split(r"(\*\*.*?\*\*)", text)
    for part in parts:
        if part.startswith("**") and part.endswith("**"):
            run = paragraph.add_run(part[2:-2])
            run.bold = True
        else:
            paragraph.add_run(part)
